### ISSUE TITLE
On a Haswell machine running OS X 10.9.5, binary outputs "Hello from x86_64!"

### ISSUE THREAD

**Issue by Wowfunhappy** [saagarjha/dummy_thicc#6]
I'm using a Hackintosh running OS X 10.9.5 (Mavericks). It has an Intel Core i7 4790K, which is a Haswell CPU.

When I run the binary, it outputs:

> Hello from x86_64!

Whereas I'd expected it to say:

> Hello from x86_64h!

If I'm just confused and this is not a bug, feel free to close!

**Comment by saagarjha** [comment]
I feel like Haswell support was added in Yosemite? Do you happen to have Haswell slices of anything in your OS? (/usr/lib/system/libsystem_m.dylib might be a good file to check.)

**Comment by Wowfunhappy** [comment]
> Do you happen to have Haswell slices of anything in your OS?

Nope. That was dumb. Mavericks definitely supports Haswell processors (see also: 2014 Macbook Air), but I guess not the Haswell-specific slice.
